//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnLeave.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offer()
        {
            this.OfferPhotoDetails = new HashSet<OfferPhotoDetail>();
        }
    
        public int OfferId { get; set; }
        public string KeyWords { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Description { get; set; }
        public int OfferTypeId { get; set; }
        public int UtilityBuildingId { get; set; }
        public Nullable<byte> Discount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferPhotoDetail> OfferPhotoDetails { get; set; }
        public virtual OfferType OfferType { get; set; }
        public virtual UtilityBuilding UtilityBuilding { get; set; }
    }
}
