//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnLeave.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferPhotoDetail
    {
        public int OfferPhotoDetailId { get; set; }
        public string KeyWords { get; set; }
        public int OfferId { get; set; }
        public int PhotoId { get; set; }
    
        public virtual Offer Offer { get; set; }
    }
}
