//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnLeave.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int RoomId { get; set; }
        public string DBC_KEYWORDS { get; set; }
        public int RoomTypeId { get; set; }
        public int UtilityBuildingId { get; set; }
        public short TotalNumber { get; set; }
        public Nullable<short> FreeNumber { get; set; }
    
        public virtual RoomType RoomType { get; set; }
        public virtual UtilityBuilding UtilityBuilding { get; set; }
    }
}
