//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnLeave.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilityBuildingFacilityType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UtilityBuildingFacilityType()
        {
            this.UtilityBuidingFacilityDetails = new HashSet<UtilityBuidingFacilityDetail>();
        }
    
        public int UtilityBuildingFacilityTypeId { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UtilityBuidingFacilityDetail> UtilityBuidingFacilityDetails { get; set; }
    }
}
