//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnLeave.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilityBuildingLocale
    {
        public int UtilityBuildingLocaleId { get; set; }
        public int UtilityBuildingId { get; set; }
        public int LocaleId { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string ContactPerson { get; set; }
        public string Address { get; set; }
    
        public virtual Locale Locale { get; set; }
        public virtual UtilityBuilding UtilityBuilding { get; set; }
    }
}
