//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnLeave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locale
    {
        public Locale()
        {
            this.UtilityBuildingLocales = new HashSet<UtilityBuildingLocale>();
        }
    
        public int LocaleId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<UtilityBuildingLocale> UtilityBuildingLocales { get; set; }
    }
}
