//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnLeave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferType
    {
        public OfferType()
        {
            this.Offers = new HashSet<Offer>();
        }
    
        public int OfferTypeId { get; set; }
        public string KeyWords { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Offer> Offers { get; set; }
    }
}
