//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnLeave.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OnLeaveContext : DbContext
    {
        public OnLeaveContext()
            : base("name=OnLeaveContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Offer> Offers { get; set; }
        public virtual DbSet<OfferPhotoDetail> OfferPhotoDetails { get; set; }
        public virtual DbSet<OfferType> OfferTypes { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<UtilityBuilding> UtilityBuildings { get; set; }
        public virtual DbSet<UtilityBuildingPhotoDetail> UtilityBuildingPhotoDetails { get; set; }
        public virtual DbSet<UtilityBuildingType> UtilityBuildingTypes { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<UtilityBuidingFacilityDetail> UtilityBuidingFacilityDetails { get; set; }
        public virtual DbSet<UtilityBuildingFacilityType> UtilityBuildingFacilityTypes { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<RoomType> RoomTypes { get; set; }
        public virtual DbSet<Period> Periods { get; set; }
        public virtual DbSet<RoomAmount> RoomAmounts { get; set; }
        public virtual DbSet<Locale> Locales { get; set; }
        public virtual DbSet<UtilityBuildingLocale> UtilityBuildingLocales { get; set; }
        public virtual DbSet<SystemType> SystemTypes { get; set; }
    
        public virtual int InsertUser(string firstName, string lastName, string email, string telephone, string password)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var telephoneParameter = telephone != null ?
                new ObjectParameter("Telephone", telephone) :
                new ObjectParameter("Telephone", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertUser", firstNameParameter, lastNameParameter, emailParameter, telephoneParameter, passwordParameter);
        }
    
        public virtual ObjectResult<GetHotelRooms_Result> GetHotelRooms(Nullable<int> utilityBuildingId)
        {
            var utilityBuildingIdParameter = utilityBuildingId.HasValue ?
                new ObjectParameter("UtilityBuildingId", utilityBuildingId) :
                new ObjectParameter("UtilityBuildingId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHotelRooms_Result>("GetHotelRooms", utilityBuildingIdParameter);
        }
    }
}
