//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnLeave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomType
    {
        public RoomType()
        {
            this.Rooms = new HashSet<Room>();
            this.RoomAmounts = new HashSet<RoomAmount>();
        }
    
        public int RoomTypeId { get; set; }
        public string DBC_KEYWORDS { get; set; }
        public string Description { get; set; }
        public short Order { get; set; }
    
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual ICollection<RoomAmount> RoomAmounts { get; set; }
    }
}
