//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnLeave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilityBuilding
    {
        public UtilityBuilding()
        {
            this.Offers = new HashSet<Offer>();
            this.UtilityBuildingPhotoDetails = new HashSet<UtilityBuildingPhotoDetail>();
            this.UtilityBuidingFacilityDetails = new HashSet<UtilityBuidingFacilityDetail>();
            this.Rooms = new HashSet<Room>();
            this.Periods = new HashSet<Period>();
            this.UtilityBuildingLocales = new HashSet<UtilityBuildingLocale>();
        }
    
        public int UtilityBuildingId { get; set; }
        public string KeyWords { get; set; }
        public int UtilityBuildingTypeId { get; set; }
        public string UserId { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<decimal> lat { get; set; }
        public Nullable<decimal> lon { get; set; }
        public Nullable<byte> Rating { get; set; }
    
        public virtual ICollection<Offer> Offers { get; set; }
        public virtual UtilityBuildingType UtilityBuildingType { get; set; }
        public virtual ICollection<UtilityBuildingPhotoDetail> UtilityBuildingPhotoDetails { get; set; }
        public virtual ICollection<UtilityBuidingFacilityDetail> UtilityBuidingFacilityDetails { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<Period> Periods { get; set; }
        public virtual ICollection<UtilityBuildingLocale> UtilityBuildingLocales { get; set; }
    }
}
