//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnLeave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilityBuildingPhotoDetail
    {
        public int UtilityBuildingPhotoDetailId { get; set; }
        public string KeyWords { get; set; }
        public int UtilityBuildingId { get; set; }
        public int PhotoId { get; set; }
    
        public virtual UtilityBuilding UtilityBuilding { get; set; }
        public virtual Photo Photo { get; set; }
    }
}
